wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1648149728
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      - 16
      4: 3.9.0
      5: 0.12.11
      8:
      - 1
      - 3
      - 5
activation_dense:
  desc: null
  value: relu
additional:
  desc: null
  value: usage of convolution
batch_size:
  desc: null
  value: 128
bidirectional:
  desc: null
  value: true
dense_first_neuron:
  desc: null
  value: 64
dense_number:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.25
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 1.0e-05
lstm_neurons:
  desc: null
  value: 128
lstm_number:
  desc: null
  value: 2
number_imu:
  desc: null
  value: 3
stride:
  desc: null
  value: 5
window_size:
  desc: null
  value: 30
