# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false  
contact_links:
- name: 🤷💻🤦 Github discussions
  url: https://github.com/EFR-AI/AIBSIF/discussions/categories/q-a
  about: Please ask typical Q&A here
